<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <ApplicationIcon>app.ico</ApplicationIcon>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net10.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseWPF>true</UseWPF>
        <!-- Ajoutez cette ligne pour forcer la correspondance avec vos x:Class -->
    <RootNamespace>SuiviPortefolio</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="Tests\**\*.cs" />
    <Compile Remove="TempQuery3\**\*.cs" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.Data.Sqlite" Version="10.0.12" />
    <PackageReference Include="OxyPlot.Core" Version="2014.1.546" />
    <PackageReference Include="OxyPlot.Wpf" Version="2014.1.546" />
  </ItemGroup>

</Project>
